// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace FinanceManager.Controllers
{
    public partial class FinancialBalanceController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected FinancialBalanceController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SumOfIncomings()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SumOfIncomings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetIncomesByTimeFilter()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncomesByTimeFilter);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetIncomingsByNumberOfDays()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncomingsByNumberOfDays);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetIncomesByNumberOfWeeks()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncomesByNumberOfWeeks);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetIncomingsByNumberOfMonth()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncomingsByNumberOfMonth);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetIncome()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncome);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetIncomesByLastOperations()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncomesByLastOperations);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SumOfOutgoings()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SumOfOutgoings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetOutgoingsByTimeFilter()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoingsByTimeFilter);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetOutgoingsByNumberOfDays()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoingsByNumberOfDays);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetOutgoingsByNumberOfWeeks()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoingsByNumberOfWeeks);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetOutgoingsByNumberOfMonth()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoingsByNumberOfMonth);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetOutgoing()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoing);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetOutgoingsByLastOperations()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoingsByLastOperations);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FinancialBalanceController Actions { get { return MVC.FinancialBalance; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "FinancialBalance";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "FinancialBalance";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string SumOfIncomings = "SumOfIncomings";
            public readonly string GetIncomesByTimeFilter = "GetIncomesByTimeFilter";
            public readonly string GetIncomingsByNumberOfDays = "GetIncomingsByNumberOfDays";
            public readonly string GetIncomesByNumberOfWeeks = "GetIncomesByNumberOfWeeks";
            public readonly string GetIncomingsByNumberOfMonth = "GetIncomingsByNumberOfMonth";
            public readonly string GetIncomes = "GetIncomes";
            public readonly string GetIncome = "GetIncome";
            public readonly string GetIncomesByLastOperations = "GetIncomesByLastOperations";
            public readonly string SumOfOutgoings = "SumOfOutgoings";
            public readonly string GetOutgoingsByTimeFilter = "GetOutgoingsByTimeFilter";
            public readonly string GetOutgoingsByNumberOfDays = "GetOutgoingsByNumberOfDays";
            public readonly string GetOutgoingsByNumberOfWeeks = "GetOutgoingsByNumberOfWeeks";
            public readonly string GetOutgoingsByNumberOfMonth = "GetOutgoingsByNumberOfMonth";
            public readonly string GetOutgoings = "GetOutgoings";
            public readonly string GetOutgoing = "GetOutgoing";
            public readonly string GetOutgoingsByLastOperations = "GetOutgoingsByLastOperations";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string SumOfIncomings = "SumOfIncomings";
            public const string GetIncomesByTimeFilter = "GetIncomesByTimeFilter";
            public const string GetIncomingsByNumberOfDays = "GetIncomingsByNumberOfDays";
            public const string GetIncomesByNumberOfWeeks = "GetIncomesByNumberOfWeeks";
            public const string GetIncomingsByNumberOfMonth = "GetIncomingsByNumberOfMonth";
            public const string GetIncomes = "GetIncomes";
            public const string GetIncome = "GetIncome";
            public const string GetIncomesByLastOperations = "GetIncomesByLastOperations";
            public const string SumOfOutgoings = "SumOfOutgoings";
            public const string GetOutgoingsByTimeFilter = "GetOutgoingsByTimeFilter";
            public const string GetOutgoingsByNumberOfDays = "GetOutgoingsByNumberOfDays";
            public const string GetOutgoingsByNumberOfWeeks = "GetOutgoingsByNumberOfWeeks";
            public const string GetOutgoingsByNumberOfMonth = "GetOutgoingsByNumberOfMonth";
            public const string GetOutgoings = "GetOutgoings";
            public const string GetOutgoing = "GetOutgoing";
            public const string GetOutgoingsByLastOperations = "GetOutgoingsByLastOperations";
        }


        static readonly ActionParamsClass_SumOfIncomings s_params_SumOfIncomings = new ActionParamsClass_SumOfIncomings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SumOfIncomings SumOfIncomingsParams { get { return s_params_SumOfIncomings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SumOfIncomings
        {
            public readonly string firstdateTime = "firstdateTime";
            public readonly string seconddateTime = "seconddateTime";
        }
        static readonly ActionParamsClass_GetIncomesByTimeFilter s_params_GetIncomesByTimeFilter = new ActionParamsClass_GetIncomesByTimeFilter();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetIncomesByTimeFilter GetIncomesByTimeFilterParams { get { return s_params_GetIncomesByTimeFilter; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetIncomesByTimeFilter
        {
            public readonly string firstDateTime = "firstDateTime";
            public readonly string secondDateTime = "secondDateTime";
        }
        static readonly ActionParamsClass_GetIncomingsByNumberOfDays s_params_GetIncomingsByNumberOfDays = new ActionParamsClass_GetIncomingsByNumberOfDays();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetIncomingsByNumberOfDays GetIncomingsByNumberOfDaysParams { get { return s_params_GetIncomingsByNumberOfDays; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetIncomingsByNumberOfDays
        {
            public readonly string days = "days";
        }
        static readonly ActionParamsClass_GetIncomesByNumberOfWeeks s_params_GetIncomesByNumberOfWeeks = new ActionParamsClass_GetIncomesByNumberOfWeeks();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetIncomesByNumberOfWeeks GetIncomesByNumberOfWeeksParams { get { return s_params_GetIncomesByNumberOfWeeks; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetIncomesByNumberOfWeeks
        {
            public readonly string weeks = "weeks";
        }
        static readonly ActionParamsClass_GetIncomingsByNumberOfMonth s_params_GetIncomingsByNumberOfMonth = new ActionParamsClass_GetIncomingsByNumberOfMonth();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetIncomingsByNumberOfMonth GetIncomingsByNumberOfMonthParams { get { return s_params_GetIncomingsByNumberOfMonth; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetIncomingsByNumberOfMonth
        {
            public readonly string month = "month";
        }
        static readonly ActionParamsClass_GetIncome s_params_GetIncome = new ActionParamsClass_GetIncome();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetIncome GetIncomeParams { get { return s_params_GetIncome; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetIncome
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetIncomesByLastOperations s_params_GetIncomesByLastOperations = new ActionParamsClass_GetIncomesByLastOperations();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetIncomesByLastOperations GetIncomesByLastOperationsParams { get { return s_params_GetIncomesByLastOperations; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetIncomesByLastOperations
        {
            public readonly string count = "count";
        }
        static readonly ActionParamsClass_SumOfOutgoings s_params_SumOfOutgoings = new ActionParamsClass_SumOfOutgoings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SumOfOutgoings SumOfOutgoingsParams { get { return s_params_SumOfOutgoings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SumOfOutgoings
        {
            public readonly string firstdateTime = "firstdateTime";
            public readonly string seconddateTime = "seconddateTime";
        }
        static readonly ActionParamsClass_GetOutgoingsByTimeFilter s_params_GetOutgoingsByTimeFilter = new ActionParamsClass_GetOutgoingsByTimeFilter();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOutgoingsByTimeFilter GetOutgoingsByTimeFilterParams { get { return s_params_GetOutgoingsByTimeFilter; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOutgoingsByTimeFilter
        {
            public readonly string firstDateTime = "firstDateTime";
            public readonly string secondDateTime = "secondDateTime";
        }
        static readonly ActionParamsClass_GetOutgoingsByNumberOfDays s_params_GetOutgoingsByNumberOfDays = new ActionParamsClass_GetOutgoingsByNumberOfDays();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOutgoingsByNumberOfDays GetOutgoingsByNumberOfDaysParams { get { return s_params_GetOutgoingsByNumberOfDays; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOutgoingsByNumberOfDays
        {
            public readonly string days = "days";
        }
        static readonly ActionParamsClass_GetOutgoingsByNumberOfWeeks s_params_GetOutgoingsByNumberOfWeeks = new ActionParamsClass_GetOutgoingsByNumberOfWeeks();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOutgoingsByNumberOfWeeks GetOutgoingsByNumberOfWeeksParams { get { return s_params_GetOutgoingsByNumberOfWeeks; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOutgoingsByNumberOfWeeks
        {
            public readonly string weeks = "weeks";
        }
        static readonly ActionParamsClass_GetOutgoingsByNumberOfMonth s_params_GetOutgoingsByNumberOfMonth = new ActionParamsClass_GetOutgoingsByNumberOfMonth();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOutgoingsByNumberOfMonth GetOutgoingsByNumberOfMonthParams { get { return s_params_GetOutgoingsByNumberOfMonth; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOutgoingsByNumberOfMonth
        {
            public readonly string month = "month";
        }
        static readonly ActionParamsClass_GetOutgoing s_params_GetOutgoing = new ActionParamsClass_GetOutgoing();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOutgoing GetOutgoingParams { get { return s_params_GetOutgoing; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOutgoing
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetOutgoingsByLastOperations s_params_GetOutgoingsByLastOperations = new ActionParamsClass_GetOutgoingsByLastOperations();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOutgoingsByLastOperations GetOutgoingsByLastOperationsParams { get { return s_params_GetOutgoingsByLastOperations; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOutgoingsByLastOperations
        {
            public readonly string count = "count";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string ManView = "ManView";
            }
            public readonly string ManView = "~/Views/FinancialBalance/ManView.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_FinancialBalanceController : FinanceManager.Controllers.FinancialBalanceController
    {
        public T4MVC_FinancialBalanceController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SumOfIncomingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.DateTime? firstdateTime, System.DateTime? seconddateTime);

        [NonAction]
        public override System.Web.Mvc.ActionResult SumOfIncomings(System.DateTime? firstdateTime, System.DateTime? seconddateTime)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SumOfIncomings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "firstdateTime", firstdateTime);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "seconddateTime", seconddateTime);
            SumOfIncomingsOverride(callInfo, firstdateTime, seconddateTime);
            return callInfo;
        }

        [NonAction]
        partial void GetIncomesByTimeFilterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.DateTime? firstDateTime, System.DateTime? secondDateTime);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetIncomesByTimeFilter(System.DateTime? firstDateTime, System.DateTime? secondDateTime)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncomesByTimeFilter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "firstDateTime", firstDateTime);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "secondDateTime", secondDateTime);
            GetIncomesByTimeFilterOverride(callInfo, firstDateTime, secondDateTime);
            return callInfo;
        }

        [NonAction]
        partial void GetIncomingsByNumberOfDaysOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? days);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetIncomingsByNumberOfDays(int? days)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncomingsByNumberOfDays);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "days", days);
            GetIncomingsByNumberOfDaysOverride(callInfo, days);
            return callInfo;
        }

        [NonAction]
        partial void GetIncomesByNumberOfWeeksOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? weeks);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetIncomesByNumberOfWeeks(int? weeks)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncomesByNumberOfWeeks);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "weeks", weeks);
            GetIncomesByNumberOfWeeksOverride(callInfo, weeks);
            return callInfo;
        }

        [NonAction]
        partial void GetIncomingsByNumberOfMonthOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? month);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetIncomingsByNumberOfMonth(int? month)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncomingsByNumberOfMonth);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "month", month);
            GetIncomingsByNumberOfMonthOverride(callInfo, month);
            return callInfo;
        }

        [NonAction]
        partial void GetIncomesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetIncomes()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncomes);
            GetIncomesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetIncomeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetIncome(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncome);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetIncomeOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void GetIncomesByLastOperationsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? count);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetIncomesByLastOperations(int? count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncomesByLastOperations);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            GetIncomesByLastOperationsOverride(callInfo, count);
            return callInfo;
        }

        [NonAction]
        partial void SumOfOutgoingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.DateTime? firstdateTime, System.DateTime? seconddateTime);

        [NonAction]
        public override System.Web.Mvc.ActionResult SumOfOutgoings(System.DateTime? firstdateTime, System.DateTime? seconddateTime)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SumOfOutgoings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "firstdateTime", firstdateTime);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "seconddateTime", seconddateTime);
            SumOfOutgoingsOverride(callInfo, firstdateTime, seconddateTime);
            return callInfo;
        }

        [NonAction]
        partial void GetOutgoingsByTimeFilterOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.DateTime? firstDateTime, System.DateTime? secondDateTime);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetOutgoingsByTimeFilter(System.DateTime? firstDateTime, System.DateTime? secondDateTime)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoingsByTimeFilter);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "firstDateTime", firstDateTime);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "secondDateTime", secondDateTime);
            GetOutgoingsByTimeFilterOverride(callInfo, firstDateTime, secondDateTime);
            return callInfo;
        }

        [NonAction]
        partial void GetOutgoingsByNumberOfDaysOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? days);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetOutgoingsByNumberOfDays(int? days)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoingsByNumberOfDays);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "days", days);
            GetOutgoingsByNumberOfDaysOverride(callInfo, days);
            return callInfo;
        }

        [NonAction]
        partial void GetOutgoingsByNumberOfWeeksOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? weeks);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetOutgoingsByNumberOfWeeks(int? weeks)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoingsByNumberOfWeeks);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "weeks", weeks);
            GetOutgoingsByNumberOfWeeksOverride(callInfo, weeks);
            return callInfo;
        }

        [NonAction]
        partial void GetOutgoingsByNumberOfMonthOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? month);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetOutgoingsByNumberOfMonth(int? month)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoingsByNumberOfMonth);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "month", month);
            GetOutgoingsByNumberOfMonthOverride(callInfo, month);
            return callInfo;
        }

        [NonAction]
        partial void GetOutgoingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetOutgoings()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoings);
            GetOutgoingsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetOutgoingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetOutgoing(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoing);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetOutgoingOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void GetOutgoingsByLastOperationsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? count);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetOutgoingsByLastOperations(int? count)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoingsByLastOperations);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "count", count);
            GetOutgoingsByLastOperationsOverride(callInfo, count);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
