// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace FinanceManager.Controllers
{
    public partial class FinancialBalanceController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected FinancialBalanceController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SumOfIncomings()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SumOfIncomings);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SumOfOutgoings()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SumOfOutgoings);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FinancialBalanceController Actions { get { return MVC.FinancialBalance; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "FinancialBalance";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "FinancialBalance";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string SumOfIncomings = "SumOfIncomings";
            public readonly string SumOfOutgoings = "SumOfOutgoings";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string SumOfIncomings = "SumOfIncomings";
            public const string SumOfOutgoings = "SumOfOutgoings";
        }


        static readonly ActionParamsClass_SumOfIncomings s_params_SumOfIncomings = new ActionParamsClass_SumOfIncomings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SumOfIncomings SumOfIncomingsParams { get { return s_params_SumOfIncomings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SumOfIncomings
        {
            public readonly string firstdateTime = "firstdateTime";
            public readonly string seconddateTime = "seconddateTime";
        }
        static readonly ActionParamsClass_SumOfOutgoings s_params_SumOfOutgoings = new ActionParamsClass_SumOfOutgoings();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SumOfOutgoings SumOfOutgoingsParams { get { return s_params_SumOfOutgoings; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SumOfOutgoings
        {
            public readonly string firstdateTime = "firstdateTime";
            public readonly string seconddateTime = "seconddateTime";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string DateMenuView = "DateMenuView";
                public readonly string IncomeAddView = "IncomeAddView";
                public readonly string IncomingListView = "IncomingListView";
                public readonly string IncomingTypeView = "IncomingTypeView";
                public readonly string ManageView = "ManageView";
                public readonly string OutgoingAddView = "OutgoingAddView";
                public readonly string OutgoingListView = "OutgoingListView";
            }
            public readonly string DateMenuView = "~/Views/FinancialBalance/DateMenuView.cshtml";
            public readonly string IncomeAddView = "~/Views/FinancialBalance/IncomeAddView.cshtml";
            public readonly string IncomingListView = "~/Views/FinancialBalance/IncomingListView.cshtml";
            public readonly string IncomingTypeView = "~/Views/FinancialBalance/IncomingTypeView.cshtml";
            public readonly string ManageView = "~/Views/FinancialBalance/ManageView.cshtml";
            public readonly string OutgoingAddView = "~/Views/FinancialBalance/OutgoingAddView.cshtml";
            public readonly string OutgoingListView = "~/Views/FinancialBalance/OutgoingListView.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_FinancialBalanceController : FinanceManager.Controllers.FinancialBalanceController
    {
        public T4MVC_FinancialBalanceController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void SumOfIncomingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.DateTime? firstdateTime, System.DateTime? seconddateTime);

        [NonAction]
        public override System.Web.Mvc.ActionResult SumOfIncomings(System.DateTime? firstdateTime, System.DateTime? seconddateTime)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SumOfIncomings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "firstdateTime", firstdateTime);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "seconddateTime", seconddateTime);
            SumOfIncomingsOverride(callInfo, firstdateTime, seconddateTime);
            return callInfo;
        }

        [NonAction]
        partial void SumOfOutgoingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.DateTime? firstdateTime, System.DateTime? seconddateTime);

        [NonAction]
        public override System.Web.Mvc.ActionResult SumOfOutgoings(System.DateTime? firstdateTime, System.DateTime? seconddateTime)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SumOfOutgoings);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "firstdateTime", firstdateTime);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "seconddateTime", seconddateTime);
            SumOfOutgoingsOverride(callInfo, firstdateTime, seconddateTime);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
