// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace FinanceManager.Controllers
{
    public partial class FinancialManagerController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected FinancialManagerController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetIncome()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncome);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult GetOutgoing()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoing);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteIncome()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteIncome);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult DeleteOutgoing()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteOutgoing);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddIncome()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddIncome);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AddOutgoing()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddOutgoing);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateIncome()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateIncome);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UpdateOutgoing()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateOutgoing);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public FinancialManagerController Actions { get { return MVC.FinancialManager; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "FinancialManager";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "FinancialManager";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string GetIncomes = "GetIncomes";
            public readonly string GetOutgoings = "GetOutgoings";
            public readonly string GetIncome = "GetIncome";
            public readonly string GetOutgoing = "GetOutgoing";
            public readonly string DeleteIncome = "DeleteIncome";
            public readonly string DeleteOutgoing = "DeleteOutgoing";
            public readonly string AddIncome = "AddIncome";
            public readonly string AddOutgoing = "AddOutgoing";
            public readonly string UpdateIncome = "UpdateIncome";
            public readonly string UpdateOutgoing = "UpdateOutgoing";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string GetIncomes = "GetIncomes";
            public const string GetOutgoings = "GetOutgoings";
            public const string GetIncome = "GetIncome";
            public const string GetOutgoing = "GetOutgoing";
            public const string DeleteIncome = "DeleteIncome";
            public const string DeleteOutgoing = "DeleteOutgoing";
            public const string AddIncome = "AddIncome";
            public const string AddOutgoing = "AddOutgoing";
            public const string UpdateIncome = "UpdateIncome";
            public const string UpdateOutgoing = "UpdateOutgoing";
        }


        static readonly ActionParamsClass_GetIncome s_params_GetIncome = new ActionParamsClass_GetIncome();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetIncome GetIncomeParams { get { return s_params_GetIncome; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetIncome
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_GetOutgoing s_params_GetOutgoing = new ActionParamsClass_GetOutgoing();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_GetOutgoing GetOutgoingParams { get { return s_params_GetOutgoing; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_GetOutgoing
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteIncome s_params_DeleteIncome = new ActionParamsClass_DeleteIncome();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteIncome DeleteIncomeParams { get { return s_params_DeleteIncome; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteIncome
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_DeleteOutgoing s_params_DeleteOutgoing = new ActionParamsClass_DeleteOutgoing();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_DeleteOutgoing DeleteOutgoingParams { get { return s_params_DeleteOutgoing; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_DeleteOutgoing
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_AddIncome s_params_AddIncome = new ActionParamsClass_AddIncome();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddIncome AddIncomeParams { get { return s_params_AddIncome; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddIncome
        {
            public readonly string income = "income";
        }
        static readonly ActionParamsClass_AddOutgoing s_params_AddOutgoing = new ActionParamsClass_AddOutgoing();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AddOutgoing AddOutgoingParams { get { return s_params_AddOutgoing; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AddOutgoing
        {
            public readonly string outgoing = "outgoing";
        }
        static readonly ActionParamsClass_UpdateIncome s_params_UpdateIncome = new ActionParamsClass_UpdateIncome();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateIncome UpdateIncomeParams { get { return s_params_UpdateIncome; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateIncome
        {
            public readonly string income = "income";
        }
        static readonly ActionParamsClass_UpdateOutgoing s_params_UpdateOutgoing = new ActionParamsClass_UpdateOutgoing();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UpdateOutgoing UpdateOutgoingParams { get { return s_params_UpdateOutgoing; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UpdateOutgoing
        {
            public readonly string outgoing = "outgoing";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string MainView = "MainView";
            }
            public readonly string MainView = "~/Views/FinancialManager/MainView.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_FinancialManagerController : FinanceManager.Controllers.FinancialManagerController
    {
        public T4MVC_FinancialManagerController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetIncomesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetIncomes()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncomes);
            GetIncomesOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetOutgoingsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetOutgoings()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoings);
            GetOutgoingsOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void GetIncomeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetIncome(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetIncome);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetIncomeOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void GetOutgoingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult GetOutgoing(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.GetOutgoing);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            GetOutgoingOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteIncomeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteIncome(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteIncome);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteIncomeOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void DeleteOutgoingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        [NonAction]
        public override System.Web.Mvc.ActionResult DeleteOutgoing(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.DeleteOutgoing);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DeleteOutgoingOverride(callInfo, id);
            return callInfo;
        }

        [NonAction]
        partial void AddIncomeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Domain.Models.Income income);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddIncome(Domain.Models.Income income)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddIncome);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "income", income);
            AddIncomeOverride(callInfo, income);
            return callInfo;
        }

        [NonAction]
        partial void AddOutgoingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Domain.Models.Outgoing outgoing);

        [NonAction]
        public override System.Web.Mvc.ActionResult AddOutgoing(Domain.Models.Outgoing outgoing)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AddOutgoing);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "outgoing", outgoing);
            AddOutgoingOverride(callInfo, outgoing);
            return callInfo;
        }

        [NonAction]
        partial void UpdateIncomeOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Domain.Models.Income income);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateIncome(Domain.Models.Income income)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateIncome);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "income", income);
            UpdateIncomeOverride(callInfo, income);
            return callInfo;
        }

        [NonAction]
        partial void UpdateOutgoingOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Domain.Models.Outgoing outgoing);

        [NonAction]
        public override System.Web.Mvc.ActionResult UpdateOutgoing(Domain.Models.Outgoing outgoing)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UpdateOutgoing);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "outgoing", outgoing);
            UpdateOutgoingOverride(callInfo, outgoing);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
